// 简体中文 —— the main process, mirroring `en.ts` key for key.
// Writing rules: `./index.ts`.
import type { DesktopCopy } from "./types";

const zh: DesktopCopy = {
  menu: {
    app: {
      about: "关于 AI4Kanban",
      checkUpdates: "检查更新…",
      services: "服务",
      hide: "隐藏 AI4Kanban",
      hideOthers: "隐藏其他",
      unhide: "全部显示",
      quit: "退出 AI4Kanban",
    },
    file: {
      title: "文件",
      open: "打开项目…",
      openRecent: "最近打开",
      close: "关闭项目",
      noRecent: "暂无其他项目",
      recent: (name) => name,
      recentGone: (name) => `${name}  （文件夹已不存在）`,
      recentRunning: (name) => `${name}  （运行中）`,
      closeWindow: "关闭窗口",
      quit: "退出",
      checkUpdates: "检查更新…",
    },
    edit: {
      title: "编辑",
      undo: "撤销",
      redo: "重做",
      cut: "剪切",
      copy: "拷贝",
      paste: "粘贴",
      pasteAndMatchStyle: "粘贴并匹配样式",
      delete: "删除",
      selectAll: "全选",
      speech: "语音",
      startSpeaking: "开始朗读",
      stopSpeaking: "停止朗读",
    },
    view: {
      title: "显示",
      back: "后退",
      forward: "前进",
      reload: "重新载入",
      forceReload: "强制重新载入",
      devTools: "开发者工具",
      actualSize: "实际大小",
      zoomIn: "放大",
      zoomOut: "缩小",
      fullScreen: "全屏",
    },
    window: {
      title: "窗口",
      minimize: "最小化",
      zoom: "缩放",
      front: "前置全部窗口",
      close: "关闭",
    },
    help: { title: "帮助", guide: "AI4Kanban 指南", downloads: "下载" },
  },
  launcher: {
    recent: "最近打开",
    language: "语言",
    soon: "即将支持",
    runningHere: "这里有任务正在运行",
    cloudBadge: "Cloud",
    opening: (name) => `正在打开 ${name}…`,
    pathGone: (path) => `${path} —— 文件夹已不存在`,
    forget: "把这个项目移出列表——磁盘上的文件不受影响",
    forgetGone: "文件夹已不存在——把它移出列表",
    local: {
      title: "本地看板",
      blurb: "就在这台机器的一个文件夹里。卡片是你仓库中的文件。",
      create: "新建本地看板",
      open: "打开本地看板",
    },
    cloud: {
      title: "Cloud 看板",
      preview: "邀请制预览",
      blurb: "由我们托管看板，在哪台机器上都能打开。项目仍然是这里的一个文件夹——你的代码和 agent 不会离开这台机器。",
      create: "新建 Cloud 看板",
      open: "打开 Cloud 看板",
      privacy: "隐私政策",
      terms: "服务条款",
      back: "返回",
      busy: "处理中…",
      signIn: {
        boundary:
          "Cloud 保存这个看板——它的卡片、记忆、发布和历史——所以你在任何一台机器上登录，打开的都是同一个看板。它不会收到你的仓库，不会运行 agent，也不会读取你没有发布的卡片。",
        button: "使用 GitHub 继续",
        confirms: (privacyLink, termsLink) => `登录即表示你已阅读${privacyLink}和${termsLink}。`,
        instead: (localLink) => `暂时不用？${localLink}——这里还没有决定任何事情。`,
      },
      closed: {
        title: "预览尚未对这个账号开放。",
        blurb: "每一份申请我们都会人工阅读。通过之后你的账号就进来了，我们会发邮件通知你。不承诺具体时间。",
        ask: "申请邀请",
        asked: (date) => `你已在 ${date} 提交申请。我们会通过邮件答复。`,
        signOut: "退出登录",
        instead: (localLink) => `不必等邀请：${localLink}，等进来之后再把它迁到 Cloud。`,
      },
      pick: {
        workspace: "工作区",
        newWorkspace: "新建工作区",
        namedBelow: "在下方命名",
        namePlaceholder: "给这个看板起个名字",
        opened: (date) => `最近写入于 ${date}`,
        folder: "这台机器上的文件夹",
        choose: "选择…",
        noFolder: "选择这个看板所属的项目文件夹",
        importCards: (count) => `把 docs/kanban/ 里已有的 ${count} 张卡片导入进来`,
        importBlurb: "文件夹里的内容不会被改动——工作区拿到的是一份副本。",
        create: "新建 Cloud 看板",
        open: "打开 Cloud 看板",
      },
      done: {
        ready: (name, cards) =>
          cards > 0
            ? `${name} 已经在 Cloud 上——${cards} 张卡片，这个检出目录现在指向它。`
            : `${name} 已经在 Cloud 上，这个检出目录现在指向它。`,
        stale: "从现在起，docs/kanban/ 里的卡片只是一份副本：看板的读写都发生在工作区。",
        offerTitle: "把这份副本移出仓库",
        offerBlurb: (cards) =>
          `一次提交：${cards} 个看板文件不再由 git 跟踪，新增 .ai4kanban.json，并把 docs/kanban/ 加进根目录的 .gitignore。工作区里的其他改动一概不会被带上。`,
        offerSafe: "无论你怎么选都不会丢东西——卡片都在 git 历史里，你在这里决定的只是要不要让 git 记录这次迁移。",
        noGit: "这里还没有 git 仓库，所以没有地方提交这个指针。看板照常可用；想要仓库的话运行 git init。",
        nothingTracked: "这里没有任何东西在 git 里，所以没有需要提交的改动。",
        commit: "提交这次改动",
        keep: "保持文件不变",
        committed: "已提交。从现在起，看板就是这个工作区。",
        openBoard: "打开看板",
      },
    },
  },
  dialog: {
    folderGone: {
      message: (name) => `${name} 已经不在了。`,
      detail: (path) => `${path}\n\n这个文件夹被移动或删除了。可以把它移出列表，或者把它放回原处。`,
    },
    pick: {
      titleFirst: "打开一个项目",
      titleAnother: "打开另一个项目",
      message: "选择要打开的项目文件夹。它还没有看板也没关系。",
      button: "打开",
    },
    command: {
      ask: "把 akb 命令加入 PATH？",
      detailWindows: (folder) =>
        `AI4Kanban 自带一份 akb——编码 Agent 驱动这个看板所用的命令。这一步会把应用自己的目录（${folder}）加入你的 PATH。更新应用就等于更新命令。\n\n新增的 PATH 只对之后新开的终端生效。\n\n之后也可以在「配置 → 通用」里完成这一步。`,
      detailLink: (path) =>
        `AI4Kanban 自带一份 akb——编码 Agent 驱动这个看板所用的命令。这一步会让 ${path} 指向应用内的那份副本，因此更新应用就等于更新命令。\n\n之后也可以在「配置 → 通用」里完成这一步。`,
      detailLinkPassword: (path) =>
        `AI4Kanban 自带一份 akb——编码 Agent 驱动这个看板所用的命令。这一步会让 ${path} 指向应用内的那份副本，因此更新应用就等于更新命令。macOS 会要求输入管理员密码才能写入那里。\n\n之后也可以在「配置 → 通用」里完成这一步。`,
      install: "安装",
      notNow: "暂不",
      failed: "akb 未能安装。",
      ready: "akb 已就绪。",
      readyWindows: "新开一个终端，运行 `akb version`。单独输入 `akb` 会打开这个应用。",
      readyLink: "在终端里运行 `akb version`。单独输入 `akb` 会在你当前所在的项目上打开这个应用。",
    },
    update: {
      newest: (version) => `AI4Kanban ${version} 已是最新版本。`,
      out: (version) => `AI4Kanban ${version} 已发布。`,
      detail: "可以在这里安装，应用会重启到新版本。",
      detailManual: (reason) => `${reason}\n\n请到下载页获取新版本。`,
      install: "安装",
      download: "下载",
      later: "稍后",
      skip: "跳过这个版本",
      downloading: "AI4Kanban 正在下载新版本。看板上方那一行会显示进度。",
      ready: (version) => `AI4Kanban ${version} 已下载完成。`,
      readyDetail: "下次重启时安装。",
      restart: "立即重启",
    },
    startFailed: "AI4Kanban 无法启动看板",
  },
  command: {
    blockedSource: "这是从源码构建的版本，不是安装好的应用——还没有可以指向的应用包。",
    blockedLinux: "Linux 版本每次运行都解压到新的位置，因此没有可以长期指向的路径。",
    blockedImage: "AI4Kanban 正从磁盘映像中运行。请先把它移入「应用程序」，再从那里打开。",
    blockedTranslocated:
      "macOS 正在运行 AI4Kanban 的一份临时副本。请先把它移入「应用程序」，再从那里打开。",
    blockedDownloads: "AI4Kanban 正从「下载」文件夹运行。请先把它移入「应用程序」，再从那里打开。",
    password: (folder) => `AI4Kanban 需要你的密码，才能把 akb 命令放进 ${folder}。`,
    cancelled: "已取消——没有写入任何内容。",
    noWay: "这个系统没有安装该命令的方式。",
    held: (path, holder) => `${path} 被${holder}占用——应用只会替换它自己写下的链接。`,
    holderUnknown: "别的东西",
    holderFile: "一个普通文件",
    holderUnreadable: "一个无法读取的符号链接",
    holderLink: (target) => `一个指向 ${target} 的符号链接`,
    missing: (path) => `这个构建里没有该命令（在 ${path} 找过）。`,
    missingScript: (path) => `这个构建里没有 PATH 脚本（在 ${path} 找过）。`,
  },
  update: {
    blockedSource: "这是从源码构建的版本，不是安装好的应用——没有可以替换的应用包。",
    blockedNotAppImage: "这个副本不是以 AppImage 方式运行的，没有单一文件可以替换。请到下载页获取新版本。",
    blockedReadOnly: (folder) => `AI4Kanban 无法写入 ${folder}，因此不能把新版本放到那里。请到下载页获取新版本。`,
    noBuild: "这个版本没有适配这台电脑的构建，需要手动下载。",
    failedRead: "AI4Kanban 读不到这个版本的发布信息，因此无法安装。",
    failedDownload: (reason) => `下载没有完成：${reason}。`,
    failedChecksum: "下载的文件与发布时公布的校验值不一致，已丢弃。这台电脑上没有任何改动。",
    failedUnpack: (reason) => `下载的文件无法解压：${reason}。`,
  },
  board: {
    installerMissing: (path) =>
      `这个构建里没有看板安装程序（在 ${path} 找过）。\n从源码构建的？请先在 desktop/ 下运行 \`npm run bundle\`。`,
    nothingMade: "安装程序没有留下看板",
  },
};

export default zh;
